### ISSUE TITLE
TextInput表单项样式问题

### ISSUE THREAD

**Issue by longniansheng** [sinoui/sinoui-forms-library#16]
sinoui-components-forms中TextInput组件不能自动填充剩余空间（包括指定multiline）

![微信图片_20190906103355](https://user-images.githubusercontent.com/17496740/64397130-b1e6b400-d092-11e9-9288-09b61dba0f37.png)

**Comment by liujinxing** [comment]
[1.0.0-alpha.12](https://github.com/sinoui/sinoui-forms-library/releases/tag/v1.0.0-alpha.12) 版本已修复此缺陷。

更新下面的依赖即可：

* @sinoui/sinoui-components-forms 1.0.0-alpha.12
